version: "3.9"

services:
  app:
    container_name: "juan_the_drinker"
    build: . #for local dev you can use this option, for prod work you should take image from ECR
   # image: 058264488016.dkr.ecr.eu-north-1.amazonaws.com/juan-drinker
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - "juan_network"

  db:
    container_name: "juan_db"
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - "juan_network"

  pgadmin:
    container_name: "juan_pgadmin"
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    networks:
      - "juan_network"

volumes:
  postgres_data:


networks:
  juan_network:
    driver: bridge
