"""Added references tables in visit model

Revision ID: 4f2de41eacf2
Revises: 
Create Date: 2024-01-19 15:24:23.586555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2de41eacf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bar',
    sa.Column('bar_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bar_id')
    )
    op.create_index(op.f('ix_bar_bar_id'), 'bar', ['bar_id'], unique=False)
    op.create_table('beverage',
    sa.Column('beverage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('codebar', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('alcoholUnits', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('beverage_id')
    )
    op.create_index(op.f('ix_beverage_beverage_id'), 'beverage', ['beverage_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('stock',
    sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('beverage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bar.bar_id'], ),
    sa.ForeignKeyConstraint(['beverage_id'], ['beverage.beverage_id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_index(op.f('ix_stock_stock_id'), 'stock', ['stock_id'], unique=False)
    op.create_table('visit',
    sa.Column('visitedOn', sa.Date(), nullable=True),
    sa.Column('visit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bar.bar_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_index(op.f('ix_visit_visit_id'), 'visit', ['visit_id'], unique=False)
    op.create_table('drink',
    sa.Column('drink_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('happy_hour', sa.Boolean(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.visit_id'], ),
    sa.PrimaryKeyConstraint('drink_id')
    )
    op.create_index(op.f('ix_drink_drink_id'), 'drink', ['drink_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drink_drink_id'), table_name='drink')
    op.drop_table('drink')
    op.drop_index(op.f('ix_visit_visit_id'), table_name='visit')
    op.drop_table('visit')
    op.drop_index(op.f('ix_stock_stock_id'), table_name='stock')
    op.drop_table('stock')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_beverage_beverage_id'), table_name='beverage')
    op.drop_table('beverage')
    op.drop_index(op.f('ix_bar_bar_id'), table_name='bar')
    op.drop_table('bar')
    # ### end Alembic commands ###
